### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by gcraenen** [uuencode/geary2txt#1]
Thanks for this tool. I was looking for it to get msg out of geary.

Getting this error:

Traceback (most recent call last):
  File "/home/gcraenen/geary2txt-master/geary2txt.py", line 180, in <module>
    subject=re.sub(r'[^a-zA-Z0-9 ]','',subject)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

**Comment by uuencode** [comment]
I can't help much as I no longer use Geary. I believe the problem was caused by a missing subject (length=0). if you replace `subject=row[2]` with `subject=row[2]+' '` it should run fine.

**Comment by gcraenen** [comment]
Ah, too bad. Tried your suggestion, but unfortunately not working:

Traceback (most recent call last):
  File "/home/gcraenen/geary2txt-master/geary2txt.py", line 179, in <module>
    subject=row[2]+' '
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by uuencode** [comment]
it tells you that row[2] is not a string, try: `subject=str(row[2]); subject=subject+' '`

**Comment by gcraenen** [comment]
That was it. Thanks a lot for your help and this script.
